apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-schema
data:
  DB_TYPE: "mongo"
  APP_GIT_URL: "https://github.com/pdevops87/roboshop-devops-project-v3/catalogue"
  DB_HOST: "mongodb-dev.pdevops78.online"
  SCHEMA_FILE: "db/master-data.js"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-schema-job
spec:
  template:
    spec:
      containers:
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          envFrom:
            - configMapRef:
                name: catalogue-schema
      restartPolicy: Never
  backoffLimit: 0






